### PR TITLE
Changes for 4.1

### PR DESCRIPTION
**Pull request by ExE-Boss**
This is my collection of fixes for version 4.1.

I’ve also dropped the `viewBox.baseVal.width !== 0` workaround since Firefox 22 isn’t supported since version 4.0.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
review?(@Ede123)

**Comment by Ede123** [comment]
Hi @ExE-Boss, sorry for not commenting earlier, I've been very busy lately.

I've had a quick look and it basically looks fine. I'm not completely sure what the implications of 9d0590e3a3bf64bb65f05858b5900cbb770bd8a6 are? Before (i.e. before webextension and Firefox Quantum) the SVG was scaled to fill the window width/height (which is what's supposed to happen when no width/height is specified as it's supposed to be interpreted as 100%) which resulted in the background being scaled wrongly and shadows being off but otherwise worked ok.

That said I discontinued using Firefox after version 57 was released and I'm not really able (or willing) to test in newer versions, so I'll trust your judgment here. Let me know if I should push this live.

**Comment by ExE-Boss** [comment]
The `width`/`height` fix from https://github.com/Ede123/nicermediapages/pull/5/commits/9d0590e3a3bf64bb65f05858b5900cbb770bd8a6 is needed to fix the issue when the SVG height is larger than the window, which causes the top to get cut off, which is what the `overflowingVertical` class fixes ([Firefox does this with normal images](https://hg.mozilla.org/mozilla-central/file/tip/layout/style/TopLevelImageDocument.css#l26)): https://github.com/Ede123/nicermediapages/blob/9d0590e3a3bf64bb65f05858b5900cbb770bd8a6/content/nicermediapages.js#L63-L70 https://github.com/Ede123/nicermediapages/blob/9d0590e3a3bf64bb65f05858b5900cbb770bd8a6/skin/nicermediapages.css#L84-L86

In any case, I’ve thoroughly tested this myself, and I’d say it’s ready to be submitted to AMO for review.

**Comment by ExE-Boss** [comment]
@Ede123 So, are you able to publish this now?

**Comment by Ede123** [comment]
I'm afraid I'm currently too busy to devote sufficient time to all my projects. On top of that I'm still not overly fond of webextensions (or rather the way Mozilla chose to force them onto its users while crippling real add-ons) and to be honest I still have not decided wether to move away from Firefox for good.

Unfortunately this makes my Firefox add-ons a rather low priority right now, and I'm very sorry for the delay this has caused in reviewing this MR. I know how frustrating slow reviews and lack of feedback from developers can be...

For that reason let me ask you: Would you be interested in becoming a maintainer for Nicer Media Pages? If it's something you'd want to do I'd assign you suitable rights, so you can commit to this repo and publish new releases on AMO. Let me know what you think...

**Comment by ExE-Boss** [comment]
Yes, I’d be interested in becoming a maintainer.

(the email I use for for AMO is the same I use on [Bugzilla](https://bugzilla.mozilla.org/user_profile?user_id=590837))

**Comment by Ede123** [comment]
I just added you as a collaborator here on GitHub and on AMO.
Feel free to ping me with any issues or questions.

Happy contributing!

**Pull request merged**
